### PR TITLE
Update MusicBeatSubstate.hx

### PR DESCRIPTION
**Pull request by Fearester**

### CODE REVIEW

**Comment by MemeHoovy** [comment]
what the hell does this fix? you just imported FlxG

**Review by MemeHoovy — APPROVED** [review]

**Comment by Akhia11** [comment]
Kys if your gay

**Comment by MemeHoovy** [comment]
> Kys if your gay

no

**Comment by Akhia11** [comment]
Ok **burning in hell**

**Comment by MemeHoovy** [comment]
> Ok **burning in hell**

nope

**Comment by Akhia11** [comment]
Yes or else 🥶🥶🥶

**Comment by MemeHoovy** [comment]
> Yes or else 🥶🥶🥶

nah

**Pull request merged**
