### PR TITLE
why not :trollface:

### PR DESCRIPTION
**Pull request by 91ebagacm**
if i miss smth u can fix (i think)

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Comment by MAJigsaw77** [comment]
I'll not steal them

**Comment by 91ebagacm** [comment]
bro u steal psych controls bruh

**Comment by MAJigsaw77** [comment]
🤨

**Comment by 91ebagacm** [comment]
u so weird nvm i will add my version

**Pull request closed without merging**
